[tool.poetry]
name = "pinto-example"
version = "0.0.1"
description = "Dummy example pure poetry pinto example"
authors = ["Alec Gunny <alec.gunny@gmail.com>"]

[tool.poetry.scripts]
testme = "pinto_example:main"

[tool.poetry.dependencies]
pip_install_test = "^0.5"
